name: Build
on: [push]

env:
  CYPRESS_INSTALL_BINARY: 0

jobs:
  www:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build www --configuration=production
